version: '3'
services:
  tesseract:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - TAG=focal-0.20
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      NVIDIA_DRIVER_CAPABILITIES: all
    container_name: tesseract_qt
    image: ghcr.io/tesseract-robotics/tesseract_qt_deploy:focal-0.20
    stdin_open: true
    tty: true
    network_mode: host
    user: ${CURRENT_UID}  # CURRENT_UID=$(id -u):$(id -g)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/hosts:/etc/hosts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]